main: me.d3x.grandexchange.GrandExchange
name: GrandExchange
version: 1.0
author: Salty
description: Player-to-Player exchange service based off of the RuneScape Grand Exchange
depend: [Zen]
commands:
  ge:
    description: opens Grand Exchange interface
    usage: /ge
